## called from ~/.bashrc

export TERM_ITALICS=true

if [ "$(uname -s)" = "Darwin" ]; then
    export CLICOLOR=1
    export GREP_OPTIONS='--color=auto'
    export LSCOLORS=exfxcxdxbxegedabagacad

    # http://drmuey.com/?do=page&id=15
    export COPYFILE_DISABLE=true
fi

## aliases
. "$HOME/.bash/aliases"

## completions

if [ "$(uname -s)" = "Darwin" ]; then
    [ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ] && \
        . "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
fi

for f in $HOME/.bash/bash_completion.d/*; do
    . $f
done

# git bash completion, before general bash_completion b/c tig completion script
if [ "$(uname -s)" = "Darwin" ]; then
    XCODE_PRE=$(xcode-select -p)
    for f in "$XCODE_PRE/usr/share/git-core/git-completion.bash" \
        "$XCODE_PRE/usr/share/git-core/git-prompt.sh"; do
        [ -r "$f" ] && . "$f"
    done
else
    for f in "/usr/share/git-core/contrib/completion/git-prompt.sh" \
        "/etc/bash_completion.d/git-prompt" \
        "/usr/share/bash-completion/completions/git"; do
        [ -r "$f" ] && . $f
    done
fi


# fzf
[ -f ~/.fzf.bash ] && . ~/.fzf.bash
## https://mike.place/2017/fzf-fd/
## ubuntu installs as "fdfind"
type "fdfind" &>/dev/null && fd=fdfind || fd=fd
export FZF_DEFAULT_COMMAND="$fd -t f"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$fd -t d"

# set the bash prompt (uses fzf, git from above)
. ~/.bash/prompt.sh

# History (after setting bash prompt)
# See bash(1) for more options
# See https://stackoverflow.com/a/19533853
export HISTFILESIZE=
export HISTSIZE=
#export HISTTIMEFORMAT="[%b %d %H:%M%] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_history_x
export HISTCONTROL=ignorespace:ignoredups:erasedups
export HISTIGNORE="&:[ ]*:exit:ls:tree:bg:fg:k1:history:clear:pwd:cd:cd *:j *:type *:brewup:ppsql"
shopt -s histappend
# multiline commands: https://askubuntu.com/a/1210371
#shopt -s cmdhist
#shopt -s lithist
# also see prompt.sh _prompt_command

# direnv
eval "$(direnv hook bash)"

# zoxide
[ -x "$(command -v zoxide)" ] && eval "$(zoxide init --cmd j bash)"

# tmux
[ "$SESSION_TYPE" = "remote/ssh" ] && export TMUX_SYM='🔒' || export TMUX_SYM='⚡'

# bc
export BC_ENV_ARGS=$HOME/.bcrc

# save last bash history
function log_bash_history {
    [[
    $(history 1) =~ ^\ *[0-9]+\ +([^\ ]+\ [^\ ]+)\ +(.*)$
    ]]
    local _dt="${BASH_REMATCH[1]}"
    local _cmd="${BASH_REMATCH[2]}"
    if [ "$_cmd" != "$PERSISTENT_HISTORY_LAST" ]
    then
        echo "$_dt $_cmd  # [$(tty)] $(pwd)" >>"$HOME/.history/bash-$(date "+%Y-%m-%d").log"
        export PERSISTENT_HISTORY_LAST="$_cmd"
    fi
}

# local bashrc
[ -f "$HOME/.bash/bashrc.local" ] && . "$HOME/.bash/bashrc.local"

# after all aliases
. ~/.bash/complete_alias
complete -F _complete_alias "${!BASH_ALIASES[@]}"
# other complete functions
complete -C /opt/homebrew/bin/terraform terraform
complete -C /opt/homebrew/bin/terraform tf
